### ISSUE TITLE
Printing Issue

### ISSUE THREAD

**Issue by xymantec** [micwallace/wallacepos#48] opened 2016-05-10 19:55 UTC
I continue to have printing issues, I have tried changing all sorts of printer settings on the UI but nothing helps. 

**Printer:** Epson TM-T20II
**PC:** Windows 7 Professional
**Server:** Ubuntu Server 14.04 LTS

**Google Chrome:**
It prints fine if after I select to cancel the print after selecting to print, it leaves a small window with the receipt image & details. If I do a print from that window The receipt prints fine like shown in picture. If I print directly from the print request I get a small cutout as shown in the picture (the last picture at the bottom of the post...), almost as if receipt info is not in place before the actual print job is requested.

** Update ** I was able to take screenshots, and it looks like my suspicion is true, it looks like for chrome the print job is created before any actually data is set to be printed, you can also see that one is printing 1 sheet and the second is printing 2. Check out the images below...

Print receipt with no cancel.
![untitled](https://cloud.githubusercontent.com/assets/6463675/15162014/a6a5f23a-16b5-11e6-9109-dcb250df8c07.png)

Print receipt canceled:
![untitled2](https://cloud.githubusercontent.com/assets/6463675/15162047/cfe6991a-16b5-11e6-849d-4574ca702bc5.png)

**IE:**
I get that long ugly receipt on the picture with no logos

**Firefox:**
Same Ugly receipt with no logos.

Any idea whats causing this issue?
![20160510_124014](https://cloud.githubusercontent.com/assets/6463675/15160429/6b7ea21c-16ae-11e6-8d3b-c467a81937c6.jpg)

**Comment by micwallace** [comment] 2016-05-11 03:42
Hey,

Thanks for providing info on this issue.
I think I know what could be causing the blank receipt in chrome.

But browser printing method is not recommended when using a thermal receipt printer.
I'm actually surprised chrome is able to print the logo!
Instead use the webprint printing method so WallacePOS can control the printer directly.
This ensures that the cash draw and cutter works correctly.

If using a USB connection you will have to set up a RAW printer in windows first:
https://qz.io/wiki/Setting-Up-A-Raw-Printer-in-Windows

Sorry about not having much documentation on printer setup at this point.
I will endevor to provide some soon.

Cheers,
Michael

**Comment by xymantec** [comment] 2016-05-11 18:02
Ok so I went ahead and set up the printer as a raw printer according to the instructions provided and I still cannot print, when I hit the print button on POS it just ignores it, I checked the print queue and and its empty it doesnt even get the print request. The WebPrint App looks like its installed as well.

![untitled3](https://cloud.githubusercontent.com/assets/6463675/15191043/aef76754-1767-11e6-8489-f84e48f0e234.png)

![untitled4](https://cloud.githubusercontent.com/assets/6463675/15191051/b49d0650-1767-11e6-92fb-d04f910c6930.png)

**Comment by Darrencwood** [comment] 2016-05-11 20:17
Hi,

We've had some success with this using the chrome kiosk-printing setting and browser printing. I did need to tweak the chrome.

Go to chrome://flags

Enable the following in this order;
Override software rendering list Mac, Windows, Linux, Chrome OS, Android
Overrides the built-in software rendering list and enables GPU-acceleration on unsupported system configurations. #ignore-gpu-blacklist
Enable

Disable the following;

3D software rasterizer Mac, Windows, Linux, Chrome OS, Android
Fall back to a 3D software rasterizer when the GPU cannot be used. #disable-software-rasterizer
Disable

Enable the following;

GPU rasterization Mac, Windows, Linux, Chrome OS, Android
Use GPU to rasterize web content. Requires impl-side painting. #enable-gpu-rasterization

Simplify page on print preview Mac, Windows, Linux, Chrome OS
Enables the simplify page check box on the print preview dialog #enable-print-preview-simplify

Zero-copy rasterizer Mac, Windows, Linux, Chrome OS, Android
Raster threads write directly to GPU memory associated with tiles. #enable-zero-copy

Let me know how you go.

I've been working on a chrome app kiosk version for our use and will contribute the details on this once I've got time.

**Comment by Darrencwood** [comment] 2016-05-11 20:19
Its caused by a delay between the rendering on the print preview and the print job being submitted by the printer , known issue with chrome on windows.

**Comment by micwallace** [comment] 2016-05-12 00:15
Thanks for providing this info Darren.

Xynantec, you may need to configure your printer as RAW. See the guide below. If it still doesn't work, check the Javascript console for any errors.

https://qz.io/wiki/Setting-Up-A-Raw-Printer-in-Windows

I have also added a printer setup guide to the FAQ

https://wallacepos.com/faq

**Comment by xymantec** [comment] 2016-05-12 16:20
Ok so i checked the console and I get this error

_GET https://192.168.1.5/docs/receipt-logo-mono.png net::ERR_SSL_PROTOCOL_ERROR_

I took it off ssl so it shouldn't be requesting a secure connection.

**Comment by micwallace** [comment] 2016-05-12 23:33
Ah okay! Aplologetically that url is probably hard coded in print.js. I'll update this afternoon!

**Comment by xymantec** [comment] 2016-05-12 23:34
no worries bro, that's what where here for :)

**Comment by micwallace** [comment] 2016-05-12 23:36
<3 open source!

**Comment by micwallace** [comment] 2016-05-13 03:28
c0fe291 will fix the ssl error.
69a33c7 will hopefully fix the rendering issue in chrome when using browser printing.

Let me know if resolved and I will close the issue.

Darrencwood, thanks for proving info on chrome kiosk mode. I will add it to the wiki a bit later.

**Comment by xymantec** [comment] 2016-05-13 06:18
It looks like it fixed the issue for just the settings page, I tried transactions>view>print and I get an error

_print.js:944 Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data._

![print](https://cloud.githubusercontent.com/assets/6463675/15239483/b842831c-1897-11e6-9c34-2b3fd1167261.png)

**Comment by micwallace** [comment] 2016-05-13 06:30
I'm pretty sure this issue has already been solved but it appears you are using an older version. Can you update to version 1.3?

Also are you using a fully qualified domain name?

**Comment by xymantec** [comment] 2016-05-13 06:38
It looks like the test print from the settings page is printing it out now but the logo is all blacked out.

![20160512_232903](https://cloud.githubusercontent.com/assets/6463675/15239834/68c06c8e-189a-11e6-98a0-ec255e7f78b9.jpg)

No I am accessing the POS locally through IP.

**Comment by xymantec** [comment] 2016-05-13 08:22
Ok I updated to the latest and it seems the receipt problem above is gone. I do have one problem though, How do i migrate all my items and configuration into the new version, I couldn't find the upgrade procedures.

**Comment by micwallace** [comment] 2016-05-13 08:43
Okay so first step is to backup your original database and connect the new installation to that database. You can do that by editing /library/wpos/.dbconfig.json with your database values.

Then just head to /installer and complete the update.
You may need to log in as admin first.

**Comment by xymantec** [comment] 2016-05-13 09:05
Everthing else seems to have loaded well but the items.

![untitled](https://cloud.githubusercontent.com/assets/6463675/15243206/117a798c-18af-11e6-9605-0e395e861a74.png)

**Comment by micwallace** [comment] 2016-05-13 10:13
Mmmm did you run the update wizard?

Try manually running the update by accessing this url:
/installer?upgrade&version=1.3

**Comment by xymantec** [comment] 2016-05-13 16:42
So... it's all finally working, the logo and everything now finally prints correctly!

I checked the console and I'm getting this on the login and home page or any page for that matter.
_utilities.js:333 Uncaught TypeError: Cannot read property '1' of null_
![print](https://cloud.githubusercontent.com/assets/6463675/15255131/08a1a7b4-18ef-11e6-8e05-baa6d284c3a9.png)


I'm not sure if I should open up a new thread for this but I figured i would just post it here.

**Comment by xymantec** [comment] 2016-05-13 17:20
I found a different problem with the receipt footer, if you remove it and then try adding it again it doesn't  show it on the print out anymore.

**Comment by micwallace** [comment] 2016-05-14 04:36
Are you using text or bitmap mode receipts?

**Comment by xymantec** [comment] 2016-05-16 19:09
nvm I got it working :)

**Closed** 2016-05-16 19:10 UTC
